#!/usr/bin/env python3
"""Install/remove only the SSH Alert hook, preserving unrelated SSH initialization."""

from pathlib import Path
import re
import sys

BEGIN = '# BEGIN SSH Alert'
END = '# END SSH Alert'
HOOK = BEGIN + '\n/opt/ssh-alert/ssh-alert-login.sh >/dev/null 2>&1 &\n' + END + '\n'


def clean_hook(text):
    text = re.sub(r'(?m)^# BEGIN SSH Alert\n.*?^# END SSH Alert\n?', '', text, flags=re.S)
    # Migrate the hook generated by earlier installers and the old manual recipe.
    if '# SSH Alert Integration' in text:
        text = re.sub(r'(?m)^if \[ -n "\$\{SSH_ALERT_DISABLED:-\}" \]; then\n'
                      r'\s*exit 0\nfi\n?', '', text)
        text = re.sub(r'(?m)^# (?:SSH Alert Integration|This script runs on every SSH login|'
                      r'Only run for interactive sessions or when explicitly requested|'
                      r'Run SSH Alert in background)\n?', '', text)
    text = re.sub(r'(?m)^\s*/opt/ssh-alert/ssh-alert(?:-enhanced)?\.sh\s*&\s*$', '', text)
    return text


def main():
    action, filename = sys.argv[1:]
    path = Path(filename)
    text = clean_hook(path.read_text() if path.exists() else '')
    if action == 'install':
        if text and not text.endswith('\n'):
            text += '\n'
        path.write_text(text + HOOK)
    elif action == 'remove':
        if not any(line.strip() and not line.lstrip().startswith('#') for line in text.splitlines()):
            if path.exists():
                path.unlink()
        else:
            path.write_text(text)
    else:
        raise ValueError('Expected install or remove')


if __name__ == '__main__':
    main()
